### ISSUE TITLE
Can't kill the King?

### ISSUE THREAD

**Issue by dom-wiecek** [MichalOSProject/Chess_Csharp#1]
I setup the board like in this screenshot. The black bishop is grey which means that the white pawn can attack but the black king is still white and cannot be attacked to finish the game.

![image](https://github.com/MichalOSProject/Chess_Csharp/assets/33128528/a6908cd2-ae2e-4956-9ee6-336b1b28902b)

**Comment by MichalOSProject** [comment]
The capture of the King is not possible according to the rules. The only way to end the game is to achieve Checkmate. In the attached Screenshot, the King can still move to the bottom left.

**Comment by dom-wiecek** [comment]
In the screenshot it is white team's turn and the king has failed to move to a safe position. This should already be checkmate. When the king is in danger, you should force the player to remove this danger by either moving the king or a different piece. So the game should never get to this screenshot.
