### ISSUE TITLE
Improve UI to show possible moves.

### ISSUE THREAD

**Issue by dom-wiecek** [MichalOSProject/Chess_Csharp#4]
With the current UI, it is difficult to see which player's turn it is and which pieces can be moved. Add some highlighting so this is easier to see. Maybe something like the below screenshot or adjust the tile colour.

![image](https://github.com/MichalOSProject/Chess_Csharp/assets/33128528/e8591c6b-c7f8-4042-b6fc-aaf063e34f50)

**Comment by MichalOSProject** [comment]
Resolved in the latest update
